refactor: update circleCi config file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,8 +1,49 @@
-version: 2.1
-orbs:
-  node: circleci/node@3.0.0
+# CicleCI Configuration File
+version: 1
+jobs:
+  prebuild:
+    docker:
+    - image: cimg/node:13.11.0
+    steps:
+    - checkout
+    - run:
+        command: |
+          if [ ! -f "package.json" ]; then
+            echo "---"
+            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
+            echo "---"
+            echo "Current directory: $(pwd)"
+            echo "List directory: "
+            ls
+            exit 1
+          fi
+        name: Checking for package.json.
+        working_directory: ~/project
+    - restore_cache:
+        keys:
+        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
+    - run:
+        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
+        name: Installing NPM packages
+        working_directory: ~/project
+    - save_cache:
+        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
+        paths:
+        - ~/.npm
+    - run:
+        command: npm run linter
+        name: Checking formatting styles...
+        working_directory: ~/project      
+    - run:
+        command: npm run start:test & npx wait-on http://localhost:8000/
+        name: Starting server for tests
+        working_directory: ~/project             
+    - run:
+        command: npm run cypress:all
+        name: Run all cypress tests
+        working_directory: ~/project
 workflows:
-  node-tests:
+  integration:
     jobs:
-      - node/test
-
+    - prebuild
+  version: 1
